return {
  dap = {
    breakpoint = " ",
    breakpoint_condition = " ",
    log_point = " ",
    stopped = " ",
    breakpoint_rejected = " ",
    pause = " ",
    play = " ",
    step_into = " ",
    step_over = " ",
    step_out = " ",
    step_back = " ",
    run_last = " ",
    terminate = " ",
  },
  misc = {
    collapsed = " ",
    expanded = " ",
    current = " ",
    folder_empty = "",
    folder_closed = "",
    folder_open = "",
    file = "",
  },
  testing = {
    expanded = "",
    child_prefix = "",
    child_indent = "",
    final_child_prefix = "",
    non_collapsible = "",
    collapsed = "",
    passed = "",
    running = "",
    failed = "",
    unknown = "",
  },
}
